### ISSUE TITLE
analyse plante en ouvrant un fichier avec ptchnl avec seulement deux dimensions

### ISSUE THREAD

**Issue by unnilennium** [ProjectMEK/communs#19]
je sais cela ne devrait pas arriver, mais en ajoutant a l'Aide D'un script des points marqués dans ptchnl je sui tombé dans le cas où ptchnl était vide avant l'ajout. Résultat en ajoutant simplement mon point ainsi 

 p.ptchnl(p.hdchnl.npoints(IndiceCanal,essai), p.hdchnl.point(IndiceCanal,essai),1)=ListePoints(essai);

ptchnl s'est retrouvé avec seulement deux dimensions.
analyse plante à l'ouverture dans communs/CFichier.m à la ligne 380 à cause du problème de dimension,

un simple fixe  après la ligne 374:  Dato =Pt.Dato;
%%ajout JP Pialasse pour ceux qui ont oublié la dimension 3
if (size(Dato,3)<2); Dato(:,:,2)=zeros(size(Dato,1),size(Dato,2),1); end; 

cela rajoute automatiquement la troisième dimension et évite le plantage.

**Comment by lemek** [comment]
Merci pour ce bug, J'ai ajouté une correction qui sera disponible à la prochaine "release".

À suivre...
